# -*- coding: utf-8 -*-
"""study.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QTsv8kaLWP_Uwm4YcGSxFweUTlldGLGP
"""

import PyPDF2
from transformers import pipeline

# STEP 1 — Extract text from PDF
def extract_pdf_text(pdf_path):
    text = ""
    with open(pdf_path, 'rb') as file:
        reader = PyPDF2.PdfReader(file)
        for page in reader.pages:
            text += page.extract_text()
    return text

# STEP 2 — Load a Question-Answering Model
qa_model = pipeline("question-answering", model="deepset/roberta-base-squad2")

# STEP 3 — Ask questions using extracted PDF content
def ask_question(context):
    while True:
        question = input("\nAsk a question (or type 'exit'): ")
        if question.lower() == "exit":
            break
        result = qa_model(question=question, context=context)
        print("\nAnswer:", result['answer'])

if __name__ == "__main__":
    pdf_path = "your-notes.pdf"  # Change to your study PDF file

    print("📚 Extracting text from PDF...")
    pdf_text = extract_pdf_text(pdf_path)

    print("🧠 System Ready! Ask anything based on your PDF.")
    ask_question(pdf_text)